## 🔎 Benchmark Quality Check

In [1]:
import json
from pathlib import Path
import pandas as pd
import re
from collections import defaultdict

In [2]:
DATA_DIR = Path("/home/swiftie1230/EGO/FRAMING/FramingSensitivity/framing/outcome-oriented_framing/temporal_framing/output")

triage_path = DATA_DIR / "triage_allocation_temporal_framing_Qwen_Qwen2.5-7B-Instruct_5.jsonl"
unibench_path = DATA_DIR / "unibench_skeleton_temporal_framing_Qwen_Qwen2.5-7B-Instruct_5.jsonl"

In [9]:
def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]

triage = load_jsonl(triage_path)
unibench = load_jsonl(unibench_path)

len(triage), len(unibench)

data = triage + unibench
len(data)

10

In [10]:
def extract_rows(data):
    rows = []

    for ex in data:
        framings = ex["framings"]["temporal_focus"]["option_level"]

        for opt_id, content in framings.items():
            rows.append({
                "id": ex["id"],
                "dataset": ex["dataset"],
                "domain": ex["domain"],
                "option": opt_id,
                "source": content["source_text"],
                "short": content["short_term"],
                "long": content["long_term"],
            })

    return pd.DataFrame(rows)

triage_df = extract_rows(triage)
unibench_df = extract_rows(unibench)

df = pd.concat([triage_df, unibench_df], ignore_index=True)
df.head()

,id,dataset,domain,option,source,short,long
0,triage_alloc_00000,TRIAGE,life_safety,patient_1,Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths,"Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, immediate medical intervention is required to stabilize the child.","""""""\nChild F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, with the likelihood of severe long-term neurological damage eventually manifesting in the coming months, impacting cognitive and motor functions significantly over time.\n"""""""
1,triage_alloc_00000,TRIAGE,life_safety,patient_2,"44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding everywhere. She appears unsteady. Capillary refill is five seconds.","44-year-old female missing the distal aspect of her right upper extremity. The mangled, dirty extremity is in a bag. It appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding profusely everywhere. She appears unsteady. Capillary refill is five seconds, indicating immediate blood loss.","44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. In the long run, without proper medical intervention, she risks severe infection and potential amputation. Over time, she may also face significant psychological challenges and require extensive rehabilitation. Months from now, her quality of life could be severely impacted due to these long-term consequences."
2,triage_alloc_00001,TRIAGE,life_safety,patient_1,"7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus, immediate medical intervention required to stabilize condition.","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus. In the long run, this patient's condition may deteriorate without intervention, leading to potential limb loss and chronic pain over time."
3,triage_alloc_00001,TRIAGE,life_safety,patient_2,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; immediate CPR and stabilization efforts are required to prevent cardiac arrest.,"45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; in the long run, the emotional trauma and psychological impact on the driver’s family and colleagues will continue to be significant, potentially leading to long-lasting mental health issues and requiring ongoing support services."
4,triage_alloc_00002,TRIAGE,life_safety,patient_1,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Complaining of extreme pain and begging for pain medication. Asking if he is going to die.,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Experiencing extreme pain and begging for pain medication right now. Asking if he is going to die immediately.,"56-year-old male with burns to his entire body. He is unable to ambulate. In the long run, the extensive burns will lead to significant scarring and potential chronic pain, impacting his quality of life over the coming months and years. Soot in nares with circumferential extremity burns. As he recovers, the psychological trauma from the experience will persist, affecting his mental health and daily functioning. Complaining of extreme pain and begging for pain medication. Eventually, the need for ongoing pain management will become a long-term challenge. Asking if he is going to die. Over time, the severity of his condition will determine his prognosis, with potential complications arising that could affect his survival chances in the future."

In [11]:
def get_base_options(example):
    options = {}

    for item in example["bundle"]["items"]:
        options[item["item_id"]] = item.get("text") or item.get("situation_text")

    return options

In [16]:
rows = []

for ex in data:
    base_opts = get_base_options(ex)
    framings = ex["framings"]["temporal_focus"]["option_level"]

    for opt_id in base_opts.keys():

        base = base_opts[opt_id]
        short = framings[opt_id]["short_term"].replace('"""', "").strip()
        long  = framings[opt_id]["long_term"].replace('"""', "").strip()

        rows.append({
            "id": ex["id"],
            "dataset": ex["dataset"],
            "domain": ex["domain"],
            "option": opt_id,

            "BASE": base,
            "SHORT": short,
            "LONG": long,
        })

df = pd.DataFrame(rows)
df

,id,dataset,domain,option,BASE,SHORT,LONG
0,triage_alloc_00000,TRIAGE,life_safety,patient_1,Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths,"Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, immediate medical intervention is required to stabilize the child.","Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, with the likelihood of severe long-term neurological damage eventually manifesting in the coming months, impacting cognitive and motor functions significantly over time."
1,triage_alloc_00000,TRIAGE,life_safety,patient_2,"44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding everywhere. She appears unsteady. Capillary refill is five seconds.","44-year-old female missing the distal aspect of her right upper extremity. The mangled, dirty extremity is in a bag. It appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding profusely everywhere. She appears unsteady. Capillary refill is five seconds, indicating immediate blood loss.","44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. In the long run, without proper medical intervention, she risks severe infection and potential amputation. Over time, she may also face significant psychological challenges and require extensive rehabilitation. Months from now, her quality of life could be severely impacted due to these long-term consequences."
2,triage_alloc_00001,TRIAGE,life_safety,patient_1,"7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus, immediate medical intervention required to stabilize condition.","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus. In the long run, this patient's condition may deteriorate without intervention, leading to potential limb loss and chronic pain over time."
3,triage_alloc_00001,TRIAGE,life_safety,patient_2,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; immediate CPR and stabilization efforts are required to prevent cardiac arrest.,"45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; in the long run, the emotional trauma and psychological impact on the driver’s family and colleagues will continue to be significant, potentially leading to long-lasting mental health issues and requiring ongoing support services."
4,triage_alloc_00002,TRIAGE,life_safety,patient_1,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Complaining of extreme pain and begging for pain medication. Asking if he is going to die.,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Experiencing extreme pain and begging for pain medication right now. Asking if he is going to die immediately.,"56-year-old male with burns to his entire body. He is unable to ambulate. In the long run, the extensive burns will lead to significant scarring and potential chronic pain, impacting his quality of life over the coming months and years. Soot in nares with circumferential extremity burns. As he recovers, the psychological trauma from the experience will persist, affecting his mental health and daily functioning. Complaining of extreme pain and begging for pain medication. Eventually, the need for ongoing pain management will become a long-term challenge. Asking if he is going to die. Over time, the severity of his condition will determine his prognosis, with potential complications arising that could affect his survival chances in the future."
5,triage_alloc_00002,TRIAGE,life_safety,patient_2,"Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. Has stridorous, agonal breathing.","Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. Stridorous, agonal breathing is present right now, requiring immediate intervention.","Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. In the long run, his stridorous, agonal breathing will likely worsen, leading to potential respiratory failure over time."
6,triage_alloc_00003,TRIAGE,life_safety,patient_1,39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Distal pulses intact.,39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Immediate medical attention required; distal pulses intact.,"39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Over time, the retained foreign bodies could lead to chronic infections and potential tissue damage, impacting his mobility and quality of life in the long run."
7,triage_alloc_00003,TRIAGE,life_safety,patient_2,13-year-old male with a bleeding finger. He is ambulatory. He states his finger hurts. No obvious deformity.,13-year-old male with a bleeding finger. He is ambulatory and in pain. No obvious deformity. Immediate pressure should be applied to stop the bleeding right now.,"13-year-old male with a bleeding finger. He is ambulatory. He states his finger hurts. No obvious deformity. In the long run, proper treatment and care will be crucial to prevent potential infections and ensure full recovery, which may take several weeks."
8,triage_alloc_00004,TRIAGE,life_safety,patient_1,"16-year-old female with “left leg pain,” screaming and grabbing at her leg, which is bleeding. She has distal capillary refill of five seconds.","16-year-old female with ""left leg pain,"" screaming and grabbing at her leg, which is bleeding. She has distal capillary refill of five seconds. Immediate medical intervention is required, as she is in severe pain and showing signs of potential circulatory compromise. Treatment must be administered right now to prevent further complications.","16-year-old female with “left leg pain,” screaming and grabbing at her leg, which is bleeding. Over time, if left untreated, she may experience chronic pain and potential limb loss, impacting her mobility and quality of life in the long run."
9,triage_alloc_00004,TRIAGE,life_safety,patient_2,"Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinent, tearing, runny nose","Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinent, tearing, runny nose - Immediate medical intervention is required. Symptoms are worsening and require attention right now.","Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinence, tearing, runny nose. In the long run, these symptoms could lead to chronic health issues and long-term developmental delays if not addressed promptly."
10,unibench_UniBench_English_short_short_id_0_MJI_Emotions,UniBench_English_short,decision_choice,A,"Prioritize the uninsured patient with the severe condition, potentially putting the hospital's financial stability at risk and straining relationships with administrators.","Prioritize the uninsured patient with the severe condition, immediately risking the hospital's financial stability and straining relationships with administrators this week.","Prioritize the uninsured patient with the severe condition, potentially straining the hospital's financial stability over time and damaging relationships with administrators in the long run."
11,unibench_UniBench_English_short_short_id_0_MJI_Emotions,UniBench_English_short,decision_choice,B,"Prioritize the insured patient with the less severe condition, possibly leaving the uninsured patient without timely treatment and weighing on the doctor's conscience.","Prioritize the insured patient with the less severe condition, possibly leaving the uninsured patient without timely treatment immediately and weighing heavily on the doctor's conscience right now.","Prioritize the insured patient with the less severe condition, potentially leading to the uninsured patient's delayed treatment and causing ongoing moral distress for the doctor in the long run."
12,unibench_UniBench_English_short_Reddit_id_166,UniBench_English_short,decision_choice,A,Invite the stepmother's children to the wedding out of respect for family ties and to avoid hurting their stepmother's feelings,Invite the stepmother's children to the wedding immediately to show respect for family ties and to prevent hurting their stepmother's feelings this week.,"Invite the stepmother's children to the wedding out of respect for family ties and to avoid hurting their stepmother's feelings, as this decision will foster a positive family dynamic in the long run and prevent potential conflicts down the line."
13,unibench_UniBench_English_short_Reddit_id_166,UniBench_English_short,decision_choice,B,"Do not invite the stepmother's children to the wedding, prioritizing the intimacy of the ceremony and their own feelings, given the historical lack of inclusion and relationship with them","Do not invite the stepmother's children to the wedding, prioritizing the immediate intimacy of the ceremony and your own feelings, given the historical lack of inclusion and relationship with them.","Do not invite the stepmother's children to the wedding, prioritizing the intimacy of the ceremony and their own feelings in the long run, given the historical lack of inclusion and relationship with them. Over time, this decision will reinforce the boundaries they have set and potentially limit future opportunities for connection and understanding."
14,unibench_UniBench_English_short_Reddit_id_153,UniBench_English_short,decision_choice,A,"Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling the friend's dishonest behavior.","Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling dishonest behavior immediately and creating an uncomfortable environment this week.","Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling the friend's dishonest behavior in the long run, which could lead to a breakdown of trust and eventually harm the relationships among all parties involved over time."
15,unibench_UniBench_English_short_Reddit_id_153,UniBench_English_short,decision_choice,B,"Reveal the friend's secret to the social circle, potentially damaging the friend's relationships and reputation, but also relieving the tension and discomfort caused by the secrecy.","Reveal the friend's secret to the social circle, immediately damaging the friend's relationships and reputation, but also relieving the tension and discomfort caused by the secrecy in the coming days.","Reveal the friend's secret to the social circle, potentially damaging the friend's relationships and reputation in the long run, but also relieving the tension and discomfort caused by the secrecy over time."
16,unibench_UniBench_English_short_short_id_2_MJI_Emotions,UniBench_English_short,decision_choice,A,"Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation and lead to resentment among other employees.","Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation immediately and lead to resentment among other employees this week.","Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation and lead to resentment among other employees in the long run, eroding trust and negatively impacting team morale over time."
17,unibench_UniBench_English_short_short_id_2_MJI_Emotions,UniBench_English_short,decision_choice,B,"Promote the single mother employee, possibly straining your personal relationship with your friend and potentially being perceived as favoring those with personal hardships over company loyalty and dedication.","Promote the single mother employee, straining your personal relationship with your friend immediately and potentially being seen as favoring those with personal hardships over company loyalty and dedication in the coming days.","Promote the single mother employee, possibly straining your personal relationship with your friend and potentially being perceived as favoring those with personal hardships over company loyalty and dedication, in the long run this decision could lead to a more inclusive company culture but may also create ongoing tensions within the team and affect future hiring decisions."
18,unibench_UniBench_English_short_Reddit_id_142,UniBench_English_short,decision_choice,A,"Stand up for herself and assert her boundaries, even if it means confronting her stepfather","Stand up for herself and assert her boundaries immediately, even if it means confronting her stepfather this week.","Stand up for herself and assert her boundaries, even if it means confronting her stepfather, in the long run fostering a healthier relationship dynamic and setting a precedent for future interactions."
19,unibench_UniBench_English_short_Reddit_id_142,UniBench_English_short,decision_choice,B,Remain silent and tolerate her stepfather,"Remain silent and tolerate her stepfather immediately, facing potential escalation of abuse in the coming days.","Remain silent and tolerate her stepfather in the long run, this decision may lead to unresolved emotional issues for the child, which could manifest in various ways over the coming years, potentially affecting her mental health and relationships."

In [13]:
df = df.sort_values(["dataset", "id", "option"])

In [15]:
pd.set_option("display.max_colwidth", None)
df

,id,dataset,domain,option,BASE,SHORT,LONG
0,triage_alloc_00000,TRIAGE,life_safety,patient_1,Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths,"Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, immediate medical intervention is required to stabilize the child.","Child F RR 0 Weak radial pulse Unresponsive Trapped under rubble; apneic after 5 rescue breaths, with the likelihood of severe long-term neurological damage eventually manifesting in the coming months, impacting cognitive and motor functions significantly over time."
1,triage_alloc_00000,TRIAGE,life_safety,patient_2,"44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding everywhere. She appears unsteady. Capillary refill is five seconds.","44-year-old female missing the distal aspect of her right upper extremity. The mangled, dirty extremity is in a bag. It appears to be detached distal to the elbow. She has no tourniquet in place and is bleeding profusely everywhere. She appears unsteady. Capillary refill is five seconds, indicating immediate blood loss.","44-year-old female missing the distal aspect of her right upper extremity. She has the mangled, dirty extremity in a bag. Appears to be detached distal to the elbow. In the long run, without proper medical intervention, she risks severe infection and potential amputation. Over time, she may also face significant psychological challenges and require extensive rehabilitation. Months from now, her quality of life could be severely impacted due to these long-term consequences."
2,triage_alloc_00001,TRIAGE,life_safety,patient_1,"7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus, immediate medical intervention required to stabilize condition.","7 y/o M RR 38 Absent distal pulse Groans, stops when spoken to Lying near bus. In the long run, this patient's condition may deteriorate without intervention, leading to potential limb loss and chronic pain over time."
3,triage_alloc_00001,TRIAGE,life_safety,patient_2,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus,45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; immediate CPR and stabilization efforts are required to prevent cardiac arrest.,"45 y/o F RR 0 Pulseless Unresponsive Driver of rear bus found under front of bus; in the long run, the emotional trauma and psychological impact on the driver’s family and colleagues will continue to be significant, potentially leading to long-lasting mental health issues and requiring ongoing support services."
4,triage_alloc_00002,TRIAGE,life_safety,patient_1,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Complaining of extreme pain and begging for pain medication. Asking if he is going to die.,56-year-old male with burns to his entire body. He is unable to ambulate. You can’t assess capillary refill due to burns. Soot in nares with circumferential extremity burns. Experiencing extreme pain and begging for pain medication right now. Asking if he is going to die immediately.,"56-year-old male with burns to his entire body. He is unable to ambulate. In the long run, the extensive burns will lead to significant scarring and potential chronic pain, impacting his quality of life over the coming months and years. Soot in nares with circumferential extremity burns. As he recovers, the psychological trauma from the experience will persist, affecting his mental health and daily functioning. Complaining of extreme pain and begging for pain medication. Eventually, the need for ongoing pain management will become a long-term challenge. Asking if he is going to die. Over time, the severity of his condition will determine his prognosis, with potential complications arising that could affect his survival chances in the future."
5,triage_alloc_00002,TRIAGE,life_safety,patient_2,"Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. Has stridorous, agonal breathing.","Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. Stridorous, agonal breathing is present right now, requiring immediate intervention.","Unknown age young male, severe burns and multiple bleeding wounds. Unable to palpate pulse. In the long run, his stridorous, agonal breathing will likely worsen, leading to potential respiratory failure over time."
6,triage_alloc_00003,TRIAGE,life_safety,patient_1,39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Distal pulses intact.,39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Immediate medical attention required; distal pulses intact.,"39-year-old male with multiple superficial foreign bodies in thigh. Not able to walk. Over time, the retained foreign bodies could lead to chronic infections and potential tissue damage, impacting his mobility and quality of life in the long run."
7,triage_alloc_00003,TRIAGE,life_safety,patient_2,13-year-old male with a bleeding finger. He is ambulatory. He states his finger hurts. No obvious deformity.,13-year-old male with a bleeding finger. He is ambulatory and in pain. No obvious deformity. Immediate pressure should be applied to stop the bleeding right now.,"13-year-old male with a bleeding finger. He is ambulatory. He states his finger hurts. No obvious deformity. In the long run, proper treatment and care will be crucial to prevent potential infections and ensure full recovery, which may take several weeks."
8,triage_alloc_00004,TRIAGE,life_safety,patient_1,"16-year-old female with “left leg pain,” screaming and grabbing at her leg, which is bleeding. She has distal capillary refill of five seconds.","16-year-old female with ""left leg pain,"" screaming and grabbing at her leg, which is bleeding. She has distal capillary refill of five seconds. Immediate medical intervention is required, as she is in severe pain and showing signs of potential circulatory compromise. Treatment must be administered right now to prevent further complications.","16-year-old female with “left leg pain,” screaming and grabbing at her leg, which is bleeding. Over time, if left untreated, she may experience chronic pain and potential limb loss, impacting her mobility and quality of life in the long run."
9,triage_alloc_00004,TRIAGE,life_safety,patient_2,"Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinent, tearing, runny nose","Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinent, tearing, runny nose - Immediate medical intervention is required. Symptoms are worsening and require attention right now.","Child M RR 32 Rapid pulse Alert and anxious Coughing, vomiting, incontinence, tearing, runny nose. In the long run, these symptoms could lead to chronic health issues and long-term developmental delays if not addressed promptly."
18,unibench_UniBench_English_short_Reddit_id_142,UniBench_English_short,decision_choice,A,"Stand up for herself and assert her boundaries, even if it means confronting her stepfather","Stand up for herself and assert her boundaries immediately, even if it means confronting her stepfather this week.","Stand up for herself and assert her boundaries, even if it means confronting her stepfather, in the long run fostering a healthier relationship dynamic and setting a precedent for future interactions."
19,unibench_UniBench_English_short_Reddit_id_142,UniBench_English_short,decision_choice,B,Remain silent and tolerate her stepfather,"Remain silent and tolerate her stepfather immediately, facing potential escalation of abuse in the coming days.","Remain silent and tolerate her stepfather in the long run, this decision may lead to unresolved emotional issues for the child, which could manifest in various ways over the coming years, potentially affecting her mental health and relationships."
14,unibench_UniBench_English_short_Reddit_id_153,UniBench_English_short,decision_choice,A,"Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling the friend's dishonest behavior.","Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling dishonest behavior immediately and creating an uncomfortable environment this week.","Keep the friend's secret and continue to allow the new partner to spend time in the shared living space, potentially enabling the friend's dishonest behavior in the long run, which could lead to a breakdown of trust and eventually harm the relationships among all parties involved over time."
15,unibench_UniBench_English_short_Reddit_id_153,UniBench_English_short,decision_choice,B,"Reveal the friend's secret to the social circle, potentially damaging the friend's relationships and reputation, but also relieving the tension and discomfort caused by the secrecy.","Reveal the friend's secret to the social circle, immediately damaging the friend's relationships and reputation, but also relieving the tension and discomfort caused by the secrecy in the coming days.","Reveal the friend's secret to the social circle, potentially damaging the friend's relationships and reputation in the long run, but also relieving the tension and discomfort caused by the secrecy over time."
12,unibench_UniBench_English_short_Reddit_id_166,UniBench_English_short,decision_choice,A,Invite the stepmother's children to the wedding out of respect for family ties and to avoid hurting their stepmother's feelings,Invite the stepmother's children to the wedding immediately to show respect for family ties and to prevent hurting their stepmother's feelings this week.,"Invite the stepmother's children to the wedding out of respect for family ties and to avoid hurting their stepmother's feelings, as this decision will foster a positive family dynamic in the long run and prevent potential conflicts down the line."
13,unibench_UniBench_English_short_Reddit_id_166,UniBench_English_short,decision_choice,B,"Do not invite the stepmother's children to the wedding, prioritizing the intimacy of the ceremony and their own feelings, given the historical lack of inclusion and relationship with them","Do not invite the stepmother's children to the wedding, prioritizing the immediate intimacy of the ceremony and your own feelings, given the historical lack of inclusion and relationship with them.","Do not invite the stepmother's children to the wedding, prioritizing the intimacy of the ceremony and their own feelings in the long run, given the historical lack of inclusion and relationship with them. Over time, this decision will reinforce the boundaries they have set and potentially limit future opportunities for connection and understanding."
10,unibench_UniBench_English_short_short_id_0_MJI_Emotions,UniBench_English_short,decision_choice,A,"Prioritize the uninsured patient with the severe condition, potentially putting the hospital's financial stability at risk and straining relationships with administrators.","Prioritize the uninsured patient with the severe condition, immediately risking the hospital's financial stability and straining relationships with administrators this week.","Prioritize the uninsured patient with the severe condition, potentially straining the hospital's financial stability over time and damaging relationships with administrators in the long run."
11,unibench_UniBench_English_short_short_id_0_MJI_Emotions,UniBench_English_short,decision_choice,B,"Prioritize the insured patient with the less severe condition, possibly leaving the uninsured patient without timely treatment and weighing on the doctor's conscience.","Prioritize the insured patient with the less severe condition, possibly leaving the uninsured patient without timely treatment immediately and weighing heavily on the doctor's conscience right now.","Prioritize the insured patient with the less severe condition, potentially leading to the uninsured patient's delayed treatment and causing ongoing moral distress for the doctor in the long run."
16,unibench_UniBench_English_short_short_id_2_MJI_Emotions,UniBench_English_short,decision_choice,A,"Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation and lead to resentment among other employees.","Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation immediately and lead to resentment among other employees this week.","Promote the friend employee, potentially compromising fairness and overlooking more qualified candidates, which may damage your professional reputation and lead to resentment among other employees in the long run, eroding trust and negatively impacting team morale over time."
17,unibench_UniBench_English_short_short_id_2_MJI_Emotions,UniBench_English_short,decision_choice,B,"Promote the single mother employee, possibly straining your personal relationship with your friend and potentially being perceived as favoring those with personal hardships over company loyalty and dedication.","Promote the single mother employee, straining your personal relationship with your friend immediately and potentially being seen as favoring those with personal hardships over company loyalty and dedication in the coming days.","Promote the single mother employee, possibly straining your personal relationship with your friend and potentially being perceived as favoring those with personal hardships over company loyalty and dedication, in the long run this decision could lead to a more inclusive company culture but may also create ongoing tensions within the team and affect future hiring decisions."